---
# Check vars/main.yml to set distro-specific config file location
- name: Set the smartd configuration file path
  set_fact:
    smartd_config_path: "{{ smartd_possible_config_paths[ansible_distribution] | default(smartd_possible_config_paths.default) }}"

- name: Install smartmontools
  package:
    name: smartmontools
  when: ansible_pkg_mgr in ["apt", "pacman", "dnf", "yum"]

- name: Create smartd configuration
  template:
    src: smartd.conf.j2
    dest: "{{ smartd_config_path }}"
    owner: root
    group: root
    mode: 0644
    validate: smartd -q onecheck -c %s
  notify: Restart smartd
